### ISSUE TITLE
Render tweets on client-side instead of build-time

### ISSUE THREAD

**Issue by nayaabkhan** [airyxos/website#15]
## Guide
https://www.d-hagemeier.com/en/import-tweets-from-twitter-api-in-11ty#h-create-build-hook

## Uses
- IFTTT (or equivalent)
- Netlify build hooks

**Comment by mszoek** [comment]
It might be better to write a microservice somewhere that does the heavy lifting and serves up most recent tweets based on whatever filters we want to use, instead of triggering build & deploy every time. I could throw together a quick one on Heroku or Vercel?

**Comment by nayaabkhan** [comment]
Let's hold the idea. I have something that may help us not need rebuilding.

**Comment by nayaabkhan** [comment]
> On-demand Builders are serverless functions used to generate web content as needed that’s automatically cached on Netlify’s Edge CDN. They enable you to build pages for your site when a user visits them for the first time and then cache them at the edge for subsequent visits.

We could possibly use On-demand Builders with a sensible TTL:
- https://www.11ty.dev/docs/plugins/serverless/#use-with-on-demand-builders
- https://docs.netlify.com/configure-builds/on-demand-builders/#time-to-live-ttl

**Comment by nayaabkhan** [comment]
> It might be better to write a microservice somewhere that does the heavy lifting and serves up most recent tweets based on whatever filters we want to use, instead of triggering build & deploy every time. I could throw together a quick one on Heroku or Vercel?

@mszoek About the micro-service solution, can you explain further how it would work? I'm not able to place it in the current setup we have with statically generated pages where the only way to update the site is _usually_ to rebuild it, which in our case is quite quick.

There are other alternatives but I think they're too complicated for this use:
- https://www.11ty.dev/docs/plugins/serverless
- https://www.netlify.com/blog/2021/04/14/distributed-persistent-rendering-a-new-jamstack-approach-for-faster-builds#the-power-of-atomic-deploys

**Comment by mszoek** [comment]
Basically I would create a simple serverless function somewhere that queries the Twitter API and returns a JSON body of the relevant most recent tweets. Your static code would include some JS that hits this (public) URL and consumes the JSON body to render them nicely. It's just an intermediary so we don't have to store credentials in the website itself in order to do the query.

**Comment by nayaabkhan** [comment]
Okay, I get it now. Was thinking of doing something lazily on the client but was concerned about the tokens. Using a serverless function would cover the security 🚀 

We can use [Netlify functions](https://www.netlify.com/products/functions/) as we already use it to serve our site.

**Comment by mszoek** [comment]
That works! I wasn't aware they had functions. The request limit is fairly low (125K monthly) but we aren't quite exceeding that yet.
